name: Cron Build
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            ubuntuversion: ["21.10", "21.04", "20.10", "20.04"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build container on ${{matrix.ubuntuversion}}
        run: UBUNTUVERSION=${{matrix.ubuntuversion}} make -C test build
      - name: Install packages on ${{matrix.ubuntuversion}}
        run: UBUNTUVERSION=${{matrix.ubuntuversion}} make -C test run

